# Generated by Django 3.1.5 on 2021-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('link', models.TextField(null=True)),
                ('company', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
