# Generated by Django 3.1.5 on 2021-03-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210321_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='bbc_news',
            new_name='BBC',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='cbc_news',
            new_name='CBC',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='global_news',
            new_name='Global',
        ),
    ]
