# Generated by Django 3.1.5 on 2021-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210321_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='Atlantic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='ESPN',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='Forbes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='Google',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='NPR',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='Time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='VOX',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='Yahoo',
            field=models.BooleanField(default=True),
        ),
    ]
